name: test
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: sobolevn/misspell-fixer-action@master
     - uses: peter-evans/create-pull-request@v2.4.4
       with:
         token: ${{ secrets.GITHUB_TOKEN }} 
