name: test
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  providers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          # 5.2 Stable
          - swift:5.2-xenial
          - swift:5.2-bionic
          - swift:5.2-focal
          - swift:5.2-centos8
          - swift:5.2-amazonlinux2
          # 5.2 Unstable
          - swiftlang/swift:nightly-5.2-xenial
          - swiftlang/swift:nightly-5.2-bionic
          # 5.3 Unstable
          - swiftlang/swift:nightly-5.3-xenial
          - swiftlang/swift:nightly-5.3-bionic
          # Master Unstable
          - swiftlang/swift:nightly-master-xenial
          - swiftlang/swift:nightly-master-bionic
          - swiftlang/swift:nightly-master-focal
          - swiftlang/swift:nightly-master-centos8
          - swiftlang/swift:nightly-master-amazonlinux2
    container: ${{ matrix.image }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 10
        run: swift test --enable-test-discovery --sanitize=thread
 
