# Controls when the action will run.
name: Spell check

on:
  pull_request:
    types: [opened, reopened]

  push:
    branches:
    - master

jobs:

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
