# Controls when the action will run.
name: Spell check

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
    - master

jobs:

  setup:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@master
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}


    - name: Spell check
      run: |
        brew install mint
        chmod +x Scripts/spell_check.sh
